nodeLinker: node-modules

packageExtensions:
  "@oclif/command@*":
    dependencies:
      chalk: "*"
      cli-ux: "*"
  "@oclif/plugin-help@*":
    dependencies:
      "@oclif/errors": "*"
  needle@*:
    dependencies:
      xml2js: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

# XXX: DO NOT CHANGE
# OSS License check correctness is reliant on this property!!!
nmHoistingLimits: "dependencies"

npmAuthToken: ${NPM_TOKEN:-no-token}
