yarnPath: ".yarn/releases/yarn-berry.cjs"

nodeLinker: node-modules

packageExtensions:
  "@oclif/command@*":
    dependencies:
      chalk: "*"
      cli-ux: "*"
  "@oclif/plugin-help@*":
    dependencies:
      "@oclif/errors": "*"
  needle@*:
    dependencies:
      xml2js: "*"