name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Build Common
      run: yarn build:common
    - name: Run tests
      run: yarn test