name: Tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Yarn Cache
      uses: actions/cache@v2
      with:
        path: '.yarn/cache'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install modules
      run: yarn --immutable
    - name: Copyright Header Checks
      run: yarn license:check
    - name: Lint dependencies
      run: yarn lint:deps
    - name: Build Common
      run: yarn build:common
    - name: Run tests
      run: yarn test