name: Bump Package Versions, Tag and Draft Release

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.STANDARD_VERSION_BUMP_PAT }}
    - name: Cache Yarn Cache
      uses: actions/cache@v2
      with:
        path: '.yarn/cache'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Use Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Git Identity
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Install Dependencies
      run: yarn --immutable

    - name: Bump and Tag
      run: |
        yarn bump
        echo "::set-output name=TAG_REF::`git describe --abbrev=0`"
      id: bump_tag

    - name: Push version bump & tags
      run: |
        git fetch
        git checkout main
        git push origin main --follow-tags

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_tag.outputs.TAG_REF }}
        release_name: Release ${{ steps.bump_tag.outputs.TAG_REF }}
        body: See CHANGELOG.md for changes
        draft: true
        prerelease: false
    
    # Signal the releases repostory to prepare a release
    - name: Prepare Release
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        repository: nitrictech/cli-releases
        event-type: prepare-release
        client-payload: '{"tag": "${{ steps.bump_tag.outputs.TAG_REF }}"}'