name: Publish to NPM on Github Release

on: 
  release:
     types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Yarn Cache
      uses: actions/cache@v2
      with:
        path: '.yarn/cache'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'
        always-auth: true

    - name: Normalize version string
      run: |
        version="${{ github.event.release.tag_name }}"
        echo "::set-output name=VERSION::`echo ${version:1}`"
      id: normalize_version

    - name: Install Dependencies
      run: yarn --immutable

    # Update version metadata to match tag version
    - name: Update Versions
      run: yarn version:all ${{ steps.normalize_version.outputs.VERSION }}

    - name: Build Common
      run: yarn build:common

    # Release Production
    - name: Publish latest to NPM
      if: "!github.event.release.prerelease"
      run: yarn publish:all
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # release RC
    - name: Publish latest RC to NPM
      if: "github.event.release.prerelease"
      run: yarn publish:all --tag rc-latest
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
