name: Publish to NPM on Github Release

on: 
  release:
     types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Yarn Cache
      uses: actions/cache@v2
      with:
        path: '.yarn/cache'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'
        always-auth: true

    - name: Install Dependencies
      run: yarn --immutable

    - name: Build Common
      run: yarn build:common

    - name: Publish to NPM
      run: yarn publish:all
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Normalize version string
      run: |
        version="${{ github.event.release.tag_name }}"
        echo "::set-output name=VERSION::`echo ${version:1}`"
      id: normalize_version
    
    # Signal the releases repostory to prepare a release
    - name: Chocolatey Release
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        repository: nitrictech/cli-chocolatey
        event-type: choco-release
        client-payload: '{"version": "${{ steps.normalize_version.outputs.VERSION }}"}'