name: Bump Package Versions, Tag and Draft Release

on:
  pull_request:
    types: [closed]
    branches:
      - 'develop'

jobs:
  version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        dry_run: true
        release_branches: main,develop
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add SHORT_SHA to outputs
      id: vars
      run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA} | cut -c1-8)"
    
    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        # Use nitric bot token to trigger release actions
        GITHUB_TOKEN: ${{ secrets.NITRIC_BOT_TOKEN }}
      with:
        prerelease: true
        tag_name: ${{ steps.tag_version.outputs.new_tag }}-rc.${{ steps.vars.outputs.sha_short }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}-rc.${{ steps.vars.outputs.sha_short }}
        body: ${{ steps.tag_version.outputs.changelog }}
        