name: Release Standalone Binaries

on:
  repository_dispatch:
    types: [release-ready]

jobs:
  readyRelease:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.tag }}

      - name: Cache Yarn Cache
        uses: actions/cache@v2
        with:
          path: '.yarn/cache'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build Binaries
        id: build_binaries
        run: yarn workspace @nitric/cli package:all

      - name: Upload Linux Binary
        id: upload-linux-binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.client_payload.url }}
          asset_path: ./packages/base/dist/nitric-linux-x64
          asset_name: nitric-linux-x64
          asset_content_type:  application/octet-stream

      - name: Upload MacOS Binary
        id: upload-macos-binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.client_payload.url }}
          asset_path: ./packages/base/dist/nitric-macos-x64
          asset_name: nitric-macos-x64
          asset_content_type: application/octet-stream

      - name: Upload Windows Binary
        id: upload-windows-binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.client_payload.url }}
          asset_path: ./packages/base/dist/nitric-windows-x64.exe
          asset_name: nitric-windows-x64
          asset_content_type: application/octet-stream