name: Bump Package Versions and Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Git Identity
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Dependencies
      run: yarn --frozen-lockfile
    - name: Bump and Tag
      run: yarn bump
    - name: Merge Master -> Develop
      run: |
        git checkout develop
        git merge --no-ff master -m "Merge version bump into develop"
        git push origin master develop --follow-tags